# Génère Strings.resx (en), Strings.fr.resx (fr) et Strings.Designer.cs depuis tools/strings.json
$ErrorActionPreference = "Stop"

function Escape-ResxXmlValue([string]$text) {
  if ($null -eq $text) { return "" }
  return $text -replace '&', '&amp;' -replace '<', '&lt;' -replace '>', '&gt;'
}

function Build-ResxContent([object[]]$entries, [string]$valueProperty) {
  $sb = [System.Text.StringBuilder]::new()
  [void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
  [void]$sb.AppendLine('<root>')
  [void]$sb.AppendLine('  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>')
  [void]$sb.AppendLine('  <resheader name="version"><value>2.0</value></resheader>')
  [void]$sb.AppendLine('  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
  [void]$sb.AppendLine('  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
  foreach ($e in $entries) {
    $k = [string]$e.key
    $v = Escape-ResxXmlValue ([string]$e.$valueProperty)
    [void]$sb.AppendLine('  <data name="' + $k + '" xml:space="preserve">')
    [void]$sb.AppendLine('    <value>' + $v + '</value>')
    [void]$sb.AppendLine('  </data>')
  }
  [void]$sb.AppendLine('</root>')
  return $sb.ToString()
}

function Build-DesignerCs([object[]]$entries) {
  $sb = [System.Text.StringBuilder]::new()
  [void]$sb.AppendLine('// <auto-generated />')
  [void]$sb.AppendLine('namespace Palisades.Properties')
  [void]$sb.AppendLine('{')
  [void]$sb.AppendLine('    public static class Strings')
  [void]$sb.AppendLine('    {')
  [void]$sb.AppendLine('        private static readonly global::System.Resources.ResourceManager ResourceManager =')
  [void]$sb.AppendLine('            new global::System.Resources.ResourceManager(typeof(Strings));')
  [void]$sb.AppendLine('')
  foreach ($e in $entries) {
    $name = [string]$e.key
    [void]$sb.AppendLine('        public static string ' + $name + ' => ResourceManager.GetString(nameof(' + $name + ')) ?? string.Empty;')
  }
  [void]$sb.AppendLine('    }')
  [void]$sb.AppendLine('}')
  return $sb.ToString()
}

$jsonPath = Join-Path $PSScriptRoot "strings.json"
if (-not (Test-Path -LiteralPath $jsonPath)) {
  [Console]::Error.WriteLine("Fichier introuvable : $jsonPath")
  exit 1
}

try {
  $parsed = Get-Content -LiteralPath $jsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
} catch {
  [Console]::Error.WriteLine("JSON invalide : $_")
  exit 1
}

$entries = if ($parsed -is [System.Array]) { @($parsed) } else { @($parsed) }

$i = 0
foreach ($entry in $entries) {
  $i++
  if ($null -eq $entry) {
    [Console]::Error.WriteLine("Entrée #$i : objet null.")
    exit 1
  }
  $key = $entry.key
  $fr = $entry.fr
  $en = $entry.en
  if ($null -eq $key -or [string]::IsNullOrWhiteSpace([string]$key)) {
    [Console]::Error.WriteLine("Entrée #$i : champ 'key' manquant ou vide.")
    exit 1
  }
  if ($null -eq $fr -or [string]::IsNullOrWhiteSpace([string]$fr)) {
    [Console]::Error.WriteLine("Entrée #$i (clé '$($entry.key)') : champ 'fr' manquant ou vide.")
    exit 1
  }
  if ($null -eq $en -or [string]::IsNullOrWhiteSpace([string]$en)) {
    [Console]::Error.WriteLine("Entrée #$i (clé '$($entry.key)') : champ 'en' manquant ou vide.")
    exit 1
  }
}

$propsDir = Join-Path $PSScriptRoot "..\Palisades.Application\Properties"
New-Item -ItemType Directory -Force -Path $propsDir | Out-Null

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$resxEn = Build-ResxContent $entries "en"
$resxFr = Build-ResxContent $entries "fr"
$designer = Build-DesignerCs $entries

[System.IO.File]::WriteAllText((Join-Path $propsDir "Strings.resx"), $resxEn, $utf8NoBom)
[System.IO.File]::WriteAllText((Join-Path $propsDir "Strings.fr.resx"), $resxFr, $utf8NoBom)
[System.IO.File]::WriteAllText((Join-Path $propsDir "Strings.Designer.cs"), $designer, $utf8NoBom)

Write-Output $entries.Count
